INSERT INTO categories(name)
VALUES
  ('Cheese'),
  ('Pepperoni'),
  ('Vegetarian'),
  ('Meat Lovers'),
  ('Hawaiian'),
  ('BBQ'),
  ('Chicken'),
  ('Seafood'),
  ('Vegan'),
  ('Margherita'),
  ('Buffalo'),
  ('Mushroom'),
  ('Supreme'),
  ('Greek'),
  ('Specialty'),
  ('Calzone'),
  ('Gluten-Free'),
  ('Sicilian'),
  ('New York Style'),
  ('Gourmet');