INSERT INTO ingredients (name)
VALUES
  ('Tomato'),
  ('Mozzarella'),
  ('Basil'),
  ('Pepperoni'),
  ('Ham'),
  ('Pineapple'),
  ('Barbecue Sauce'),
  ('Chicken'),
  ('Onion'),
  ('Mushroom'),
  ('Bell Pepper'),
  ('Olives'),
  ('Sausage'),
  ('Bacon'),
  ('Ground Beef'),
  ('Cheddar Cheese'),
  ('Garlic'),
  ('Spinach'),
  ('Feta Cheese'),
  ('Parmesan Cheese');